sonar.projectKey=shibare-framework_framework
sonar.organization=shibare-framework

sonar.php.coverage.reportPaths=coverage.xml
sonar.sources=src
sonar.tests=tests,src/Cache/Tests,src/Clock/Tests,src/Config/Tests,src/Console/Tests,src/Container/Tests,src/Contracts/Tests,src/Database/Tests,src/EventDispatcher/Tests,src/HttpClient/Tests,src/HttpFactory/Tests,src/HttpMessage/Tests,src/HttpServer/Tests,src/IdlOpenApi/Tests,src/Log/Tests
